### ISSUE TITLE
Requests not being captured

### ISSUE THREAD

**Issue by uriklar** [500tech/bdsm#141]
Hi guys, trying to use the plugin but not seeing any requests being captured. 

The only request being captured is to `http://localhost:8080/7e90c440248dd1482b1d.hot-update.json
`
My development requests are not to localhost:8080 but to an separate API.  
I'm using webpack with react-hot-loader

Is there something i'm missing? 
Thanks, 
Uri

**Comment by morsdyce** [comment]
Hi Uri,

Is there a chance your requests are stuck in a pending state?
BDSM currently only captures requests that have been completed, so the requests need to fail first before they show up in the UI.

Try to set a timeout on the requests and see if that helps

**Comment by uriklar** [comment]
I have several working requests and another for a non-existing endpoint the fails with 404, but none of them appear in the UI.

One important details I forgot to mention is that the requests are being made in a web worker. Maybe that's the issue?

**Comment by morsdyce** [comment]
Yeah, that's probably the issue as the web worker runs in a different context.

I'd appreciate If you could setup a small example project with a request in a web worker and I'll work on adding support for this.

Thanks

**Comment by uriklar** [comment]
https://github.com/uriklar/bdsm-web-worker-example

**Comment by morsdyce** [comment]
I've been working on this feature and now have an initial version you can try out. 
There are still a few issues and challenges I need to sort out but in general it should be usable.
For example a currently known bug forces you to refresh the page in order to update the mock data.

You can install the "next" version by running:
`npm i -S bdsm@next`

You can also see my updated fork on how to use the new version:
https://github.com/morsdyce/bdsm-web-worker-example

**Comment by morsdyce** [comment]
This feature has been implemented fully on the next branch and will be released in the next release.

You can install the "next" version by running:
`npm i -S bdsm@next`

Please note that the next version is experimental and may have some bugs.

Please refer to this repository on how to capture web worker requests:
https://github.com/morsdyce/bdsm-web-worker-example
